// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHI7aHD-FpxEu0djUfvyMFJ3Y4XL-ZrSg',
    appId: '1:548203551726:web:0790cedd3987f8ea0b4cff',
    messagingSenderId: '548203551726',
    projectId: 'maelstrom-2aa1c',
    authDomain: 'maelstrom-2aa1c.firebaseapp.com',
    storageBucket: 'maelstrom-2aa1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-7BRwTPdg06vJ3JMZgmf7i0sqkFEqWq0',
    appId: '1:548203551726:android:33c90c88305d03670b4cff',
    messagingSenderId: '548203551726',
    projectId: 'maelstrom-2aa1c',
    storageBucket: 'maelstrom-2aa1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmE74Q7VlgUWS6eVWEKhPu1H5xRH9hMuI',
    appId: '1:548203551726:ios:814fce15e3a555d20b4cff',
    messagingSenderId: '548203551726',
    projectId: 'maelstrom-2aa1c',
    storageBucket: 'maelstrom-2aa1c.appspot.com',
    iosClientId: '548203551726-78l82ptsu6k4p1s0a3eco2gv96t3h0vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.maelstrom',
  );
}
